create Dice Game and added test module
this-is-shivamsingh/greed_game pull request #1
Opened 2023-08-01 14:31 UTC by this-is-shivamsingh

Please review the code

2023-08-03 07:54 UTC, gotunandan requested changes
Please make the requested changes

2023-08-03 07:54 UTC, gotunandan commented on helper.rb
> +end
please add a new line at EOF

2023-08-03 07:54 UTC, gotunandan commented on helper.rb
> +end
This is needed for all files below this as well

2023-08-03 07:54 UTC, gotunandan commented on diceGame.rb
> +def set_user_score(currentPlayerIdx, totalScore)
Please use 2 space indentation instead of 4

2023-08-03 07:54 UTC, gotunandan commented on diceGame.rb
> +def set_user_score(currentPlayerIdx, totalScore)
You can follow this convention https://gist.github.com/gotunandan/f886e6bac00a0d3aa0512a41af7d7d20

2023-08-03 07:54 UTC, gotunandan commented on diceGame.rb
> +    $no_of_player = gets
Not seeing this prompt
Also should check for valid inputs

```
root@bebec318b125:/rancher-desktop/greed_game# ruby index.rb
a
No of Players should be greater than 0
/rancher-desktop/greed_game/diceGame.rb:42:in `play_your_turn': undefined method `+' for nil:NilClass (NoMethodError)
	from /rancher-desktop/greed_game/diceGame.rb:110:in `startGame'
	from index.rb:2:in `<main>'
root@bebec318b125:/rancher-desktop/greed_game#
```

2023-08-03 07:54 UTC, gotunandan commented on diceGame.rb
> +    if currentScore == 0 && totalScore < $min_score
There is a bug here.

player 2 has scored 500, but it still does not consider it

```
Player 2 rolls: 1 3 3 3 1
Score in this turn: 500
Player 2 needs to have a score greater than 300 in single turn, before scores get acculumated
Player 2 TOTAL SCORE: 0
```

2023-08-03 11:47 UTC, this-is-shivamsingh commented on helper.rb
> +end
Resolved

2023-08-03 11:51 UTC, this-is-shivamsingh commented on diceGame.rb
> +    if currentScore == 0 && totalScore < $min_score
Issue resides in,
play_your_turn function, where breaking the statement when non_scoring_dice == 0, but not updating totalScore .
Status: Resolved.

2023-08-03 12:51 UTC, gotunandan commented on diceGame.rb
> +    if currentScore == 0 && totalScore < $min_score
This Looks good

2023-08-03 12:52 UTC, gotunandan requested changes
The bug is fixed, but I can still see multiple places where 4 space indentation is being used instead of 2.
See line 20 21 and line 22 for example.

All functions have 4 space indentation for the first line

2023-08-03 15:44 UTC, this-is-shivamsingh commented
Change indentation from 4 to 2 in latest commit. 
Do you also suggest any vs code plugin to do so like - preittier for js ?

2023-08-04 06:33 UTC, gotunandan approved these changes
Looks good to me

2023-08-04 07:02 UTC, this-is-shivamsingh commented
PR approved, closing this PR

2023-08-04 07:02 UTC, closed without merging